version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/codedeploy

permissions:
  - object: /var/www/codedeploy
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 60
      runas: root
